export const data= [
    {
        id:1,
        title:"Idly Sambhar",
        category: "breakfast",
        img: "food_image/idly-sambhar.jpg",  
                    
    },
    {
        id:2,
        title:"Bhature",   
        category: "breakfast",
        img: "food_image/bhature.jpg",            
    },
    {
        id:3,
        title:"Daal-Baati-Churma",   
        category: "breakfast",
        img: "food_image/daal-baati-churma.jpg",            
    },
    {
        id:4,
        title:"Dhokla",   
        category: "breakfast",
        img: "food_image/dhokla.jpg",            
    },
    {
        id:5,
        title:"Chole Bhature",   
        category: "breakfast",
        img: "food_image/chole-bhature.jpg",            
    },
    {
        id:6,
        title:"Lachha Pratha",   
        category: "breakfast",
        img: "food_image/lachha-pratha.jpg",            
    },
    {
        id:7,
        title:"Litti Chokha",   
        category: "breakfast",
        img: "food_image/litti-chokha.jpg",            
    },
    {
        id:8,
        title:"Masala Dosa",   
        category: "breakfast",
        img: "food_image/masala-dosa.jpg",            
    },
    {
        id:9,
        title:"Paav Bhaji",   
        category: "breakfast",
        img: "food_image/paav-bhaji.jpg",            
    },
    {
        id:10,
        title:"Sabji Kachori",   
        category: "breakfast",
        img: "food_image/sabji-kachori.jpg",            
    },
    {
        id:11,
        title:"Sarson Saag Makki Di Roti",   
        category: "breakfast",
        img: "food_image/sarson-saag-makki-roti.jpg",            
    },
    {
        id:12,
        title:"Uttapam",   
        category: "breakfast",
        img: "food_image/uttapam.jpg",            
    },
    {
        id:13,
        title:"Undhiyo",   
        category: "breakfast",
        img: "food_image/undhiyo.jpg",            
    },
    {
        id:14,
        title:"Vada Pav",   
        category: "breakfast",
        img: "food_image/vada-pav.jpg",            
    },
    {
        id:15,
        title:"Butter Chicken",   
        category: "lunch",
        img: "food_image/butter-chicken.jpg",            
    },
    {
        id:16,
        title:"Chicken",   
        category: "lunch",
        img: "food_image/chicken.jpg",            
    },
    {
        id:17,
        title:"Chicken Biryani",   
        category: "lunch",
        img: "food_image/biryani.jpg",            
    },
    {
        id:18,
        title:"Punjabi Kadhi",   
        category: "lunch",
        img: "food_image/punjabi-kadhi.jpg",            
    },
    {
        id:19,
        title:"Thali",   
        category: "lunch",
        img: "food_image/thali.jpg",            
    },
    {
        id:20,
        title:"Shahi Paneer",   
        category: "lunch",
        img: "food_image/shahi-paneer.jpg",            
    },
    {
        id:21,
        title:"Kebabs",   
        category: "dinner",
        img: "food_image/kebabs.jpg",            
    },
    {
        id:22,
        title:"Kati Roll",   
        category: "dinner",
        img: "food_image/kati-roll.jpg",            
    },
    {
        id:23,
        title:"Kakori Kebab",   
        category: "dinner",
        img: "food_image/kakori-kebab.jpg",            
    },
    {
        id:24,
        title:"Dahi Vada",   
        category: "dinner",
        img: "food_image/dahi-vada.jpg",            
    },
    {
        id:25,
        title:"Baigan Bharta",   
        category: "lunch",
        img: "food_image/baigan-bharta.jpg",            
    },
    {
        id:26,
        title:"Kachori",   
        category: "dinner",
        img: "food_image/kachori.jpg",            
    },
    {
        id:27,
        title:"Aam Panna",   
        category: "drink",
        img: "food_image/aam-panna-drink.jpg",            
    },
    {
        id:28,
        title:"Mango Juice",   
        category: "drink",
        img: "food_image/mango-juice-drink.jpg",            
    },
    {
        id:29,
        title:"Masala Lassi",   
        category: "drink",
        img: "food_image/Masala-Lassi-drink.jpg",            
    },
    {
        id:30,
        title:"Mishti Doi",   
        category: "desert",
        img: "food_image/Mishti_Doi.jpg",            
    },
    {
        id:31,
        title:"Shikanji- Indian Lemonade",   
        category: "drink",
        img: "food_image/shikanji-indianLemonade-drink.jpg",            
    },
    {
        id:32,
        title:"Tandoori Chicken",   
        category: "dinner",
        img: "food_image/tandoori-chicken.jpg",            
    },
    {
        id:33,
        title:"Rasogollah",   
        category: "desert",
        img: "food_image/rasogollah.jpg",            
    },
    {
        id:34,
        title:"Ras Malai",   
        category: "desert",
        img: "food_image/ras-malai.jpg",            
    },
    {
        id:35,
        title:"Rabdi",   
        category: "desert",
        img: "food_image/rabdi.jpg",            
    },
    {
        id:36,
        title:"Panjiri",   
        category: "desert",
        img: "food_image/panjiri.jpg",            
    },
    {
        id:37,
        title:"Mawa-Kachori",   
        category: "desert",
        img: "food_image/mawa-kachori.jpg",            
    },
    {
        id:38,
        title:"Gulab Jamun",   
        category: "desert",
        img: "food_image/gulab-jamun.jpg",            
    },
    {
        id:39,
        title:"Gajar Ka Halwa",   
        category: "desert",
        img: "food_image/gajar-ka-halwa.jpg",            
    },
    {
        id:40,
        title:"Bhelpuri",   
        category: "snacks",
        img: "food_image/bhelpuri-snacks.jpg",            
    },
    {
        id:41,
        title:"French Fries",   
        category: "snacks",
        img: "food_image/french-fries-snaccks.jpg",            
    },
    {
        id:42,
        title:"Mirchi Vada",   
        category: "snacks",
        img: "food_image/Mirchi-vada-snacks.jpg",            
    },
    {
        id:43,
        title:"Panipuri",   
        category: "snacks",
        img: "food_image/panipuri-snacks.jpg",            
    },
    {
        id:44,
        title:"Papri Chat",   
        category: "snacks",
        img: "food_image/papri-chat-snacks.jpg",            
    },
    {
        id:45,
        title:"Potato Chips",   
        category: "snacks",
        img: "food_image/potato-chips-snacks.jpg",            
    },
    {
        id:46,
        title:"Samosa",   
        category: "snacks",
        img: "food_image/samosa-snacks.jpg",            
    },
    {
        id:47,
        title:"Papad",   
        category: "snacks",
        img: "food_image/papad.jpg",            
    },
]